// Mock data for map screen development — matches shape of getBusinessesWithVouchers return type.
// Brighton centre: 50.8503, -0.1368

const now = Date.now();
const in30Days = now + 30 * 24 * 60 * 60 * 1000;
const in60Days = now + 60 * 24 * 60 * 60 * 1000;

export const MOCK_BUSINESSES = [
  {
    _id: "mock_business_1" as never,
    _creationTime: now - 10 * 24 * 60 * 60 * 1000,
    userId: "mock_user",
    name: "Ten Tonne Tattoos",
    slug: "ten-tonne-tattoos",
    description: "Tattoos and piercings in the heart of Brighton",
    websiteUrl: "https://tentонnetattoos.co.uk",
    address: "12 Gardner Street, Brighton BN1 1UP",
    latitude: 50.8218,
    longitude: -0.1374,
    industryId: "mock_industry_1" as never,
    industry: { _id: "mock_industry_1" as never, _creationTime: now, name: "Tattoos & Piercing", category: "Beauty", slug: "tattoos-piercing" },
    logoUrl: "https://picsum.photos/seed/tattoo/400/400",
    vouchers: [
      {
        _id: "mock_voucher_1" as never,
        _creationTime: now - 2 * 24 * 60 * 60 * 1000,
        businessId: "mock_business_1" as never,
        userId: "mock_user",
        title: "Walk in Wednesday",
        description: "£50 small tattoos and two for £90. All Wednesdays, June–August 2026.",
        voucherValidFrom: now,
        voucherValidTo: in60Days,
      },
    ],
  },
  {
    _id: "mock_business_2" as never,
    _creationTime: now - 8 * 24 * 60 * 60 * 1000,
    userId: "mock_user",
    name: "Your Local Coffee",
    slug: "your-local-coffee",
    description: "Specialty coffee and fresh bakes in the North Laine.",
    websiteUrl: "https://yourlocalcoffee.co.uk",
    address: "34 Sydney Street, Brighton BN1 4EP",
    latitude: 50.8265,
    longitude: -0.1389,
    industryId: "mock_industry_2" as never,
    industry: { _id: "mock_industry_2" as never, _creationTime: now, name: "Coffee", category: "Food & Drink", slug: "coffee" },
    logoUrl: "https://picsum.photos/seed/coffee/400/400",
    vouchers: [
      {
        _id: "mock_voucher_2" as never,
        _creationTime: now - 1 * 24 * 60 * 60 * 1000,
        businessId: "mock_business_2" as never,
        userId: "mock_user",
        title: "Free pastry with a large",
        description: "Get a free pastry with any large hot drink, every day until end of July.",
        voucherValidFrom: now,
        voucherValidTo: in30Days,
      },
    ],
  },
  {
    _id: "mock_business_3" as never,
    _creationTime: now - 6 * 24 * 60 * 60 * 1000,
    userId: "mock_user",
    name: "Neon & Nostalgia",
    slug: "neon-and-nostalgia",
    description: "Retro arcade bar with craft beers and cocktails.",
    websiteUrl: "https://neonandnostalgia.co.uk",
    address: "7 Pool Valley, Brighton BN1 1NJ",
    latitude: 50.8195,
    longitude: -0.1413,
    industryId: "mock_industry_3" as never,
    industry: { _id: "mock_industry_3" as never, _creationTime: now, name: "Bar", category: "Food & Drink", slug: "bar" },
    logoUrl: "https://picsum.photos/seed/neon/400/400",
    vouchers: [
      {
        _id: "mock_voucher_3" as never,
        _creationTime: now - 3 * 24 * 60 * 60 * 1000,
        businessId: "mock_business_3" as never,
        userId: "mock_user",
        title: "High Score Date Night",
        description: "Two cocktails + unlimited arcade play for £35. Fridays and Saturdays.",
        voucherValidFrom: now,
        voucherValidTo: in30Days,
      },
    ],
  },
  {
    _id: "mock_business_4" as never,
    _creationTime: now - 4 * 24 * 60 * 60 * 1000,
    userId: "mock_user",
    name: "Cracked Mug & Bookery",
    slug: "cracked-mug-bookery",
    description: "Second-hand books, specialty teas, and cosy reading nooks.",
    websiteUrl: "https://crackedmugbookery.co.uk",
    address: "55 Gloucester Road, Brighton BN1 4AQ",
    latitude: 50.8301,
    longitude: -0.1357,
    industryId: "mock_industry_4" as never,
    industry: { _id: "mock_industry_4" as never, _creationTime: now, name: "Café", category: "Food & Drink", slug: "cafe" },
    logoUrl: "https://picsum.photos/seed/bookery/400/400",
    vouchers: [
      {
        _id: "mock_voucher_4" as never,
        _creationTime: now - 5 * 24 * 60 * 60 * 1000,
        businessId: "mock_business_4" as never,
        userId: "mock_user",
        title: "Midnight page-turner pass",
        description: "Stay after closing for a private reading session with tea included. Fridays only.",
        voucherValidFrom: now,
        voucherValidTo: in60Days,
      },
    ],
  },
  {
    _id: "mock_business_5" as never,
    _creationTime: now - 3 * 24 * 60 * 60 * 1000,
    userId: "mock_user",
    name: "Whittle & Wave",
    slug: "whittle-and-wave",
    description: "Handcrafted wooden homewares made in Brighton.",
    websiteUrl: "https://whittleandwave.co.uk",
    address: "22 Church Road, Hove BN3 2FN",
    latitude: 50.8289,
    longitude: -0.1621,
    industryId: "mock_industry_5" as never,
    industry: { _id: "mock_industry_5" as never, _creationTime: now, name: "Shop", category: "Retail", slug: "shop" },
    logoUrl: "https://picsum.photos/seed/whittle/400/400",
    vouchers: [
      {
        _id: "mock_voucher_5" as never,
        _creationTime: now - 4 * 24 * 60 * 60 * 1000,
        businessId: "mock_business_5" as never,
        userId: "mock_user",
        title: "Custom Engraving Upgrade",
        description: "Free personalised engraving on any item over £40.",
        voucherValidFrom: now,
        voucherValidTo: in30Days,
      },
    ],
  },
  {
    _id: "mock_business_6" as never,
    _creationTime: now - 2 * 24 * 60 * 60 * 1000,
    userId: "mock_user",
    name: "Root & Radical",
    slug: "root-and-radical",
    description: "Independent florist specialising in wild and seasonal arrangements.",
    websiteUrl: "https://rootandradical.co.uk",
    address: "88 Western Road, Brighton BN1 2LB",
    latitude: 50.8234,
    longitude: -0.1512,
    industryId: "mock_industry_6" as never,
    industry: { _id: "mock_industry_6" as never, _creationTime: now, name: "Florist", category: "Retail", slug: "florist" },
    logoUrl: "https://picsum.photos/seed/florist/400/400",
    vouchers: [
      {
        _id: "mock_voucher_6" as never,
        _creationTime: now - 1 * 24 * 60 * 60 * 1000,
        businessId: "mock_business_6" as never,
        userId: "mock_user",
        title: '"Mystery Cutting" Punch Card',
        description: "10 stamps gets you a free seasonal bouquet, chosen by our florists.",
        voucherValidFrom: now,
        voucherValidTo: in60Days,
      },
    ],
  },
];

// Latest offers — all vouchers sorted by _creationTime descending
export const MOCK_LATEST_VOUCHERS = MOCK_BUSINESSES.flatMap((b) =>
  b.vouchers.map((v) => ({
    ...v,
    businessName: b.name,
    industryName: b.industry?.name ?? "",
  }))
).sort((a, b) => b._creationTime - a._creationTime);
