/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// It should not be manually edited.

// Placeholder file - will be regenerated by `vinxi dev` or `vinxi build`.
// Run the dev server once to regenerate this file with proper types.

import { createFileRoute } from '@tanstack/react-router'

export interface FileRoutesByPath {
  '/': {
    id: '/'
    path: '/'
    fullPath: '/'
    preLoaderRoute: typeof import('./routes/index').Route
    parentRoute: typeof rootRoute
  }
  '/v/$id': {
    id: '/v/$id'
    path: '/v/$id'
    fullPath: '/v/$id'
    preLoaderRoute: typeof import('./routes/v/$id').Route
    parentRoute: typeof rootRoute
  }
}

import { RootRoute } from '@tanstack/react-router'

export const rootRoute = new RootRoute()

export const IndexRoute = createFileRoute('/')({
  component: () => null,
})

export const VIdRoute = createFileRoute('/v/$id')({
  component: () => null,
})

export const routeTree = rootRoute.addChildren([IndexRoute, VIdRoute])
