/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignInImport } from './routes/sign-in'
import { Route as IndexImport } from './routes/index'
import { Route as SignInSplatImport } from './routes/sign-in.$'
import { Route as BCreateImport } from './routes/b/create'
import { Route as BSlugImport } from './routes/b/$slug'
import { Route as BSlugEditImport } from './routes/b/$slug.edit'

// Create/Update Routes

const SignInRoute = SignInImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SignInSplatRoute = SignInSplatImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => SignInRoute,
} as any)

const BCreateRoute = BCreateImport.update({
  id: '/b/create',
  path: '/b/create',
  getParentRoute: () => rootRoute,
} as any)

const BSlugRoute = BSlugImport.update({
  id: '/b/$slug',
  path: '/b/$slug',
  getParentRoute: () => rootRoute,
} as any)

const BSlugEditRoute = BSlugEditImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => BSlugRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInImport
      parentRoute: typeof rootRoute
    }
    '/b/$slug': {
      id: '/b/$slug'
      path: '/b/$slug'
      fullPath: '/b/$slug'
      preLoaderRoute: typeof BSlugImport
      parentRoute: typeof rootRoute
    }
    '/b/create': {
      id: '/b/create'
      path: '/b/create'
      fullPath: '/b/create'
      preLoaderRoute: typeof BCreateImport
      parentRoute: typeof rootRoute
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatImport
      parentRoute: typeof SignInImport
    }
    '/b/$slug/edit': {
      id: '/b/$slug/edit'
      path: '/edit'
      fullPath: '/b/$slug/edit'
      preLoaderRoute: typeof BSlugEditImport
      parentRoute: typeof BSlugImport
    }
  }
}

// Create and export the route tree

interface SignInRouteChildren {
  SignInSplatRoute: typeof SignInSplatRoute
}

const SignInRouteChildren: SignInRouteChildren = {
  SignInSplatRoute: SignInSplatRoute,
}

const SignInRouteWithChildren =
  SignInRoute._addFileChildren(SignInRouteChildren)

interface BSlugRouteChildren {
  BSlugEditRoute: typeof BSlugEditRoute
}

const BSlugRouteChildren: BSlugRouteChildren = {
  BSlugEditRoute: BSlugEditRoute,
}

const BSlugRouteWithChildren = BSlugRoute._addFileChildren(BSlugRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRouteWithChildren
  '/b/$slug': typeof BSlugRouteWithChildren
  '/b/create': typeof BCreateRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/b/$slug/edit': typeof BSlugEditRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRouteWithChildren
  '/b/$slug': typeof BSlugRouteWithChildren
  '/b/create': typeof BCreateRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/b/$slug/edit': typeof BSlugEditRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRouteWithChildren
  '/b/$slug': typeof BSlugRouteWithChildren
  '/b/create': typeof BCreateRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/b/$slug/edit': typeof BSlugEditRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/b/$slug'
    | '/b/create'
    | '/sign-in/$'
    | '/b/$slug/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/b/$slug'
    | '/b/create'
    | '/sign-in/$'
    | '/b/$slug/edit'
  id:
    | '__root__'
    | '/'
    | '/sign-in'
    | '/b/$slug'
    | '/b/create'
    | '/sign-in/$'
    | '/b/$slug/edit'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SignInRoute: typeof SignInRouteWithChildren
  BSlugRoute: typeof BSlugRouteWithChildren
  BCreateRoute: typeof BCreateRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SignInRoute: SignInRouteWithChildren,
  BSlugRoute: BSlugRouteWithChildren,
  BCreateRoute: BCreateRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/sign-in",
        "/b/$slug",
        "/b/create"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/sign-in": {
      "filePath": "sign-in.tsx",
      "children": [
        "/sign-in/$"
      ]
    },
    "/b/$slug": {
      "filePath": "b/$slug.tsx",
      "children": [
        "/b/$slug/edit"
      ]
    },
    "/b/create": {
      "filePath": "b/create.tsx"
    },
    "/sign-in/$": {
      "filePath": "sign-in.$.tsx",
      "parent": "/sign-in"
    },
    "/b/$slug/edit": {
      "filePath": "b/$slug.edit.tsx",
      "parent": "/b/$slug"
    }
  }
}
ROUTE_MANIFEST_END */
