/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// It should not be manually edited.

// Placeholder file - will be regenerated by `vinxi dev` or `vinxi build`.
// Run the dev server once to regenerate this file with proper types.

import { createFileRoute } from '@tanstack/react-router'
import { RootRoute } from '@tanstack/react-router'

export interface FileRoutesByPath {
  '/': {
    id: '/'
    path: '/'
    fullPath: '/'
    preLoaderRoute: typeof import('./routes/index').Route
    parentRoute: typeof rootRoute
  }
  '/sign-in': {
    id: '/sign-in'
    path: '/sign-in'
    fullPath: '/sign-in'
    preLoaderRoute: typeof import('./routes/sign-in').Route
    parentRoute: typeof rootRoute
  }
  '/b/create': {
    id: '/b/create'
    path: '/b/create'
    fullPath: '/b/create'
    preLoaderRoute: typeof import('./routes/b/create').Route
    parentRoute: typeof rootRoute
  }
  '/b/$slug': {
    id: '/b/$slug'
    path: '/b/$slug'
    fullPath: '/b/$slug'
    preLoaderRoute: typeof import('./routes/b/$slug').Route
    parentRoute: typeof rootRoute
  }
  '/b/$slug/edit': {
    id: '/b/$slug/edit'
    path: '/b/$slug/edit'
    fullPath: '/b/$slug/edit'
    preLoaderRoute: typeof import('./routes/b/$slug.edit').Route
    parentRoute: typeof rootRoute
  }
}

export const rootRoute = new RootRoute()

export const IndexRoute = createFileRoute('/')({\n  component: () => null,\n})
export const SignInRoute = createFileRoute('/sign-in')({\n  component: () => null,\n})
export const BCreateRoute = createFileRoute('/b/create')({\n  component: () => null,\n})
export const BSlugRoute = createFileRoute('/b/$slug')({\n  component: () => null,\n})
export const BSlugEditRoute = createFileRoute('/b/$slug/edit')({\n  component: () => null,\n})

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  SignInRoute,
  BCreateRoute,
  BSlugRoute,
  BSlugEditRoute,
])
