/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as DashboardVouchersRouteImport } from './routes/dashboard/vouchers'
import { Route as DashboardPilotFeaturesRouteImport } from './routes/dashboard/pilot-features'
import { Route as DashboardBusinessesRouteImport } from './routes/dashboard/businesses'
import { Route as DashboardAuditLogRouteImport } from './routes/dashboard/audit-log'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard/analytics'
import { Route as ApiLocationRouteImport } from './routes/api/location'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => SignInRoute,
} as any)
const DashboardVouchersRoute = DashboardVouchersRouteImport.update({
  id: '/vouchers',
  path: '/vouchers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPilotFeaturesRoute = DashboardPilotFeaturesRouteImport.update({
  id: '/pilot-features',
  path: '/pilot-features',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBusinessesRoute = DashboardBusinessesRouteImport.update({
  id: '/businesses',
  path: '/businesses',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAuditLogRoute = DashboardAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiLocationRoute = ApiLocationRouteImport.update({
  id: '/api/location',
  path: '/api/location',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/sign-in': typeof SignInRouteWithChildren
  '/api/location': typeof ApiLocationRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/audit-log': typeof DashboardAuditLogRoute
  '/dashboard/businesses': typeof DashboardBusinessesRoute
  '/dashboard/pilot-features': typeof DashboardPilotFeaturesRoute
  '/dashboard/vouchers': typeof DashboardVouchersRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRouteWithChildren
  '/api/location': typeof ApiLocationRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/audit-log': typeof DashboardAuditLogRoute
  '/dashboard/businesses': typeof DashboardBusinessesRoute
  '/dashboard/pilot-features': typeof DashboardPilotFeaturesRoute
  '/dashboard/vouchers': typeof DashboardVouchersRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/sign-in': typeof SignInRouteWithChildren
  '/api/location': typeof ApiLocationRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/audit-log': typeof DashboardAuditLogRoute
  '/dashboard/businesses': typeof DashboardBusinessesRoute
  '/dashboard/pilot-features': typeof DashboardPilotFeaturesRoute
  '/dashboard/vouchers': typeof DashboardVouchersRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/sign-in'
    | '/api/location'
    | '/dashboard/analytics'
    | '/dashboard/audit-log'
    | '/dashboard/businesses'
    | '/dashboard/pilot-features'
    | '/dashboard/vouchers'
    | '/sign-in/$'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/api/location'
    | '/dashboard/analytics'
    | '/dashboard/audit-log'
    | '/dashboard/businesses'
    | '/dashboard/pilot-features'
    | '/dashboard/vouchers'
    | '/sign-in/$'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/sign-in'
    | '/api/location'
    | '/dashboard/analytics'
    | '/dashboard/audit-log'
    | '/dashboard/businesses'
    | '/dashboard/pilot-features'
    | '/dashboard/vouchers'
    | '/sign-in/$'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  SignInRoute: typeof SignInRouteWithChildren
  ApiLocationRoute: typeof ApiLocationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof SignInRoute
    }
    '/dashboard/vouchers': {
      id: '/dashboard/vouchers'
      path: '/vouchers'
      fullPath: '/dashboard/vouchers'
      preLoaderRoute: typeof DashboardVouchersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pilot-features': {
      id: '/dashboard/pilot-features'
      path: '/pilot-features'
      fullPath: '/dashboard/pilot-features'
      preLoaderRoute: typeof DashboardPilotFeaturesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/businesses': {
      id: '/dashboard/businesses'
      path: '/businesses'
      fullPath: '/dashboard/businesses'
      preLoaderRoute: typeof DashboardBusinessesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/audit-log': {
      id: '/dashboard/audit-log'
      path: '/audit-log'
      fullPath: '/dashboard/audit-log'
      preLoaderRoute: typeof DashboardAuditLogRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/location': {
      id: '/api/location'
      path: '/api/location'
      fullPath: '/api/location'
      preLoaderRoute: typeof ApiLocationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardAuditLogRoute: typeof DashboardAuditLogRoute
  DashboardBusinessesRoute: typeof DashboardBusinessesRoute
  DashboardPilotFeaturesRoute: typeof DashboardPilotFeaturesRoute
  DashboardVouchersRoute: typeof DashboardVouchersRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardAuditLogRoute: DashboardAuditLogRoute,
  DashboardBusinessesRoute: DashboardBusinessesRoute,
  DashboardPilotFeaturesRoute: DashboardPilotFeaturesRoute,
  DashboardVouchersRoute: DashboardVouchersRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface SignInRouteChildren {
  SignInSplatRoute: typeof SignInSplatRoute
}

const SignInRouteChildren: SignInRouteChildren = {
  SignInSplatRoute: SignInSplatRoute,
}

const SignInRouteWithChildren =
  SignInRoute._addFileChildren(SignInRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  SignInRoute: SignInRouteWithChildren,
  ApiLocationRoute: ApiLocationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
