export const counties = [
  "Bedfordshire",
  "Berkshire",
  "Bristol",
  "Buckinghamshire",
  "Cambridgeshire",
  "Cheshire",
  "Cornwall",
  "County Durham",
  "Cumbria",
  "Derbyshire",
  "Devon",
  "Dorset",
  "East Riding of Yorkshire",
  "East Sussex",
  "Essex",
  "Gloucestershire",
  "Greater London",
  "Greater Manchester",
  "Hampshire",
  "Herefordshire",
  "Hertfordshire",
  "Isle of Wight",
  "Kent",
  "Lancashire",
  "Leicestershire",
  "Lincolnshire",
  "Merseyside",
  "Norfolk",
  "North Somerset",
  "North Yorkshire",
  "Northamptonshire",
  "Northumberland",
  "Nottinghamshire",
  "Oxfordshire",
  "Rutland",
  "Shropshire",
  "Somerset",
  "South Gloucestershire",
  "South Yorkshire",
  "Staffordshire",
  "Suffolk",
  "Surrey",
  "Tyne and Wear",
  "Warwickshire",
  "West Midlands",
  "West Sussex",
  "West Yorkshire",
  "Wiltshire",
  "Worcestershire",
  "Aberdeenshire",
  "Angus",
  "Argyll & Bute",
  "Ayrshire",
  "Banffshire",
  "Berwickshire",
  "Caithness",
  "Clackmannanshire",
  "Dumfries & Galloway",
  "East Ayrshire",
  "East Dunbartonshire",
  "East Lothian",
  "East Renfrewshire",
  "Fife",
  "Highland",
  "Inverclyde",
  "Kincardineshire",
  "Lanarkshire",
  "Midlothian",
  "Moray",
  "North Ayrshire",
  "North Lanarkshire",
  "Orkney",
  "Perth & Kinross",
  "Renfrewshire",
  "Scottish Borders",
  "Shetland",
  "South Ayrshire",
  "South Lanarkshire",
  "Stirlingshire",
  "West Dunbartonshire",
  "West Lothian",
  "Western Isles",
  "Blaenau Gwent",
  "Bridgend",
  "Caerphilly",
  "Cardiff",
  "Carmarthenshire",
  "Ceredigion",
  "Conwy",
  "Denbighshire",
  "Flintshire",
  "Gwynedd",
  "Isle of Anglesey",
  "Merthyr Tydfil",
  "Monmouthshire",
  "Neath Port Talbot",
  "Newport",
  "Pembrokeshire",
  "Powys",
  "Rhondda Cynon Taf",
  "Swansea",
  "Torfaen",
  "Vale of Glamorgan",
  "Wrexham",
  "Antrim",
  "Armagh",
  "Down",
  "Fermanagh",
  "Londonderry",
  "Tyrone",
];
